### PR TITLE
Only get package deps if there is info available

### PR DESCRIPTION
**Pull request by steckerhalter**
I didn't thoroughly investigate the issue the last time in issue #47 and was ok with the workaround you had added. But know this is affecting other people as well.

If I understand it correctly the problem occurs because `async-bytecomp` is trying to get the dependencies of the package that is to be compiled to allow them to be async-bytecompiled as well.

It is trying to get that information from `package-archive-contents` but that's not a reliable source for this kind of information because anybody can install packages with `package-install-file` which does not populate `package-archive-contents` (because there is no package-archive involved).

I suggest therefore that it first checks if the info is available and if not, it doesn't try any further.

affects https://github.com/vyp/evil-quick-scope/issues/1

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Thanks, fixed differently.

**Comment by steckerhalter** [comment]
Thanks. I was having a look at your fix. I think this will still fail in some occasions.

That's why I had added an explicit check for the package. In case someone is using a package archive `package-archive-contents` will be non-nil but may still not contain the required info (if said package is not part of the package archive) which will throw an error again.

Could you correct that?

**Comment by thierryvolpiatto** [comment]
steckerhalter <notifications@github.com> writes:

> Could you correct that?

Should be good now.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by steckerhalter** [comment]
Thanks, looks good now...

**Pull request closed without merging**
